#!/usr/bin/env php
<?php

require_once __DIR__.'/../../../vendor/autoload.php';

use Ayuco\Listener;
use Ayuco\Commands\SetupCommand;
use Ayuco\Commands\SetNameCommand;

$ayuco = new Listener();

$ayuco->register(new SetupCommand);
$ayuco->register(new SetNameCommand(__DIR__));

$ayuco->interpret();